/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

typedef struct _NSZone NSZone;

typedef struct __IOHIDDevice* IOHIDDeviceRef;

typedef struct {
	float _field1;
	float _field2;
	float _field3;
	float _field4;
} XXStruct_n9corA;

typedef struct __CFRunLoop* CFRunLoopRef;

typedef struct __IOHIDManager* IOHIDManagerRef;

typedef struct SCRCMathAverageValue {
	unsigned samples;
	float fifo[50];
	int fifoIndex;
	float sum;
	float average;
	float current;
} SCRCMathAverageValue;

typedef struct __GSEvent* GSEventRef;

typedef struct __IOHIDValue* IOHIDValueRef;

typedef struct __CFRunLoopSource* CFRunLoopSourceRef;

typedef struct __IOHIDEventSystemClient* IOHIDEventSystemClientRef;

typedef struct {
	int _field1;
	int _field2;
	CGPoint _field3;
	CGPoint _field4;
	unsigned _field5;
	unsigned long long _field6;
	void* _field7;
	int _field8;
	int _field9;
	unsigned _field10;
	unsigned char _field11[0];
} XXStruct_uk_lJC;

typedef struct __IOHIDEvent* IOHIDEventRef;

typedef struct __AXObserver* AXObserverRef;

typedef struct __AXUIElement* AXUIElementRef;


