/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol ATLVoiceParserDelegate <NSObject>
-(void)voiceParser:(id)parser didDetectCommand:(id)command;
@optional
-(void)voiceParserDidStopListening:(id)voiceParser;
-(void)voiceParserDidStartListening:(id)voiceParser;
@end

