/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "assistivetouchd-Structs.h"

@protocol HNDAccessibilityManagerDelegate;

__attribute__((visibility("hidden")))
@interface HNDAccessibilityManager : XXUnknownSuperclass {
	AXObserverRef _axEventObserver;
	id<HNDAccessibilityManagerDelegate> _delegate;
}
@property(assign, nonatomic) id<HNDAccessibilityManagerDelegate> delegate;
+(id)sharedManager;
-(id)springBoardApplication;
-(id)currentApplication;
-(id)systemWideElement;
-(void)_firstResponderChanged;
-(void)_screenChanged;
-(void)handleSystemWideServerDied;
-(void)_initializeAXRuntime;
-(void)_observerRegistration:(BOOL)registration;
-(void)dealloc;
-(id)init;
@end

