/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "assistivetouchd-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface HNDAXElement : XXUnknownSuperclass {
	AXUIElementRef _elementRef;
}
@property(readonly, assign, nonatomic) AXUIElementRef elementRef;
+(id)elementWithAXUIElement:(AXUIElementRef)axuielement;
+(id)systemWideElement;
-(id)description;
-(BOOL)isEqual:(id)equal;
-(BOOL)press;
-(id)elementsMatchingText:(id)text;
-(BOOL)doesHaveTraits:(unsigned long long)traits;
-(id)bundleId;
-(BOOL)isScreenLocked;
-(id)firstResponder;
-(id)springBoardApplication;
-(id)currentApplication;
-(id)_valueForAttribute:(int)attribute;
-(void)_performAction:(int)action parameter:(id)parameter;
-(id)_valueForParameterizedAttribute:(int)parameterizedAttribute parameter:(id)parameter;
-(id)_elementForAttribute:(int)attribute;
-(id)initWithAXUIElement:(AXUIElementRef)axuielement;
@end

