/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol HNDDeviceDelegate <NSObject>
-(void)device:(id)device didPostEvent:(id)event;
-(void)device:(id)device didUnload:(BOOL)unload;
@end

