/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "assistivetouchd-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@protocol HNDDeviceDelegate;

__attribute__((visibility("hidden")))
@interface HNDDevice : XXUnknownSuperclass {
	IOHIDDeviceRef _hidDevice;
	id<HNDDeviceDelegate> _delegate;
	char* _hidReportBuffer;
	BOOL _isLoaded;
	BOOL _secondaryButton;
	BOOL _tertiaryButton;
	BOOL _wheel;
	float _minY;
	float _maxY;
	float _minX;
	float _maxX;
}
@property(assign, nonatomic) id<HNDDeviceDelegate> delegate;
@property(readonly, assign, nonatomic) BOOL wheel;
@property(readonly, assign, nonatomic) BOOL tertiaryButton;
@property(readonly, assign, nonatomic) BOOL secondaryButton;
@property(readonly, assign, nonatomic) BOOL isLoaded;
+(id)createNewDevice:(IOHIDDeviceRef)device;
-(void)unload;
-(BOOL)load;
-(void)handleValueCallback:(IOHIDValueRef)callback;
-(void)handleReportCallback:(int)callback report:(char*)report reportLength:(long)length;
-(void)dealloc;
-(id)_initWithHIDDevice:(IOHIDDeviceRef)hiddevice;
@end

