/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "assistivetouchd-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@protocol HNDDeviceDetectorDelegate;

__attribute__((visibility("hidden")))
@interface HNDDeviceDetector : XXUnknownSuperclass {
	IOHIDManagerRef _hidManager;
	id<HNDDeviceDetectorDelegate> _delegate;
	BOOL _detectDevices;
}
@property(assign, nonatomic) id<HNDDeviceDetectorDelegate> delegate;
@property(assign, nonatomic) BOOL detectDevices;
+(void)initialize;
+(id)sharedDetector;
-(id)_matchingDictionaries;
-(id)init;
@end

