/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "assistivetouchd-Structs.h"
#import "NSObject.h"


@protocol HNDDeviceDetectorDelegate <NSObject>
-(void)deviceDetector:(id)detector didFindDevice:(IOHIDDeviceRef)device;
@end

