/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "HNDDeviceDetectorDelegate.h"
#import "HNDDeviceDelegate.h"
#import "assistivetouchd-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface HNDDeviceManager : XXUnknownSuperclass <HNDDeviceDetectorDelegate, HNDDeviceDelegate> {
	BOOL _detectDevices;
	NSMutableArray* _devices;
	double _lastMoveTimeX;
	double _lastMoveTimeY;
	float _allowedMoveRate;
}
@property(assign, nonatomic) BOOL detectDevices;
+(void)initialize;
+(id)sharedManager;
-(int)deviceCount;
-(int)deviceCountWithSecondaryButtons;
-(void)device:(id)device didPostEvent:(id)event;
-(void)device:(id)device didUnload:(BOOL)unload;
-(void)deviceDetector:(id)detector didFindDevice:(IOHIDDeviceRef)device;
-(id)init;
@end

