/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "assistivetouchd-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface HNDEventMatchPair : XXUnknownSuperclass {
	CGPoint point;
	double time;
}
@property(assign, nonatomic) double time;
@property(assign, nonatomic) CGPoint point;
@end

