/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "assistivetouchd-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface HNDEvent : XXUnknownSuperclass {
	int _type;
	CGPoint _location;
	float _deltaX;
	float _deltaY;
}
@property(assign, nonatomic) float deltaY;
@property(assign, nonatomic) float deltaX;
@property(assign, nonatomic) CGPoint location;
@property(assign, nonatomic) int type;
-(id)description;
@end

