/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "assistivetouchd-Structs.h"
#import "HNDView.h"

@class NSMutableArray, HNDHoverCursorCircle, UIImageView;

__attribute__((visibility("hidden")))
@interface HNDFingerView : HNDView {
	NSMutableArray* _marks;
	HNDHoverCursorCircle* _hoverCursorCircle;
	HNDHoverCursorCircle* _pressedHoverCursorCircle;
	float _implodeMultiplier;
	BOOL _implodeDirectionIsUp;
	BOOL _actualVisibility;
	BOOL _finishedImplosion;
	UIImageView* _cursorImage;
	UIImageView* _pressCursorImage;
}
@property(readonly, assign, nonatomic) BOOL finishedImplosion;
@property(readonly, assign, nonatomic) float radius;
@property(assign, nonatomic) BOOL selected;
+(CGSize)fingerSize;
-(void)setVisible:(BOOL)visible animated:(BOOL)animated;
-(BOOL)isVisible;
-(void)_setIsActuallyVisible;
-(void)setFrame:(CGRect)frame;
-(float)implode:(BOOL)implode;
-(BOOL)isUserInteractionEnabled;
-(void)cancelImplodeAnimation;
-(void)implodeDisplayLinkFired:(id)fired;
-(float)explode:(BOOL)explode;
-(void)dealloc;
-(void)setIsPinchFinger:(int)finger;
-(id)initWithFrame:(CGRect)frame;
-(void)_initializeMarks;
-(void)_resetOriginalMarkLocations;
-(void)_resetHoverCircleShadow;
-(void)_setHoverCursorShadow:(id)shadow;
@end

