/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "HNDDevice.h"


__attribute__((visibility("hidden")))
@interface HNDGamePadDevice : HNDDevice {
}
-(void)handleReportCallback:(int)callback report:(char*)report reportLength:(long)length;
@end

