/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "assistivetouchd-Structs.h"
#import "HNDAccessibilityManagerDelegate.h"

@class HNDEventManager, NSArray, NSMutableArray, NSMutableDictionary, HNDView, HNDDisplayManager, HNDCustomGesture, AXTimer;

__attribute__((visibility("hidden")))
@interface HNDHandManager <HNDAccessibilityManagerDelegate> {
	HNDDisplayManager* _displayManager;
	HNDEventManager* _eventManager;
	int _orientation;
	BOOL _firstButtonDown;
	BOOL _secondButtonDown;
	CGPoint _currentLocation;
	NSMutableArray* _recordedFingers;
	int _fingerRecordCount;
	NSArray* _savedGestures;
	CGPoint _pinchAdjustLocation;
	BOOL _isMultiFinger;
	BOOL _isRecording;
	BOOL _finishedRecording;
	BOOL _isInternal;
	float _touchSpeed;
	int _thirdButtonMeaning;
	BOOL _openMenuWithSwaggle;
	BOOL _hardwareEnabled;
	BOOL _alwaysShowMenu;
	BOOL _voiceControl;
	NSArray* _customGestures;
	HNDCustomGesture* _currentCustomGesture;
	BOOL _performingGesture;
	AXTimer* _fingerDownTimer;
	BOOL _fingerDownLock;
	BOOL _fingerDownLockSawFirstUp;
	BOOL _adjustingPinch;
	BOOL _inMultiFingerGesture;
	BOOL _resettingPinch;
	HNDView* _realSelectedPinchFinger;
	CGPoint _realPinchFingerStartPoint;
	NSMutableDictionary* _avPlayers;
}
@property(readonly, assign, nonatomic) BOOL isVoiceControlRunning;
@property(readonly, assign, nonatomic) float volumeLevel;
@property(retain, nonatomic) NSArray* customGestures;
@property(assign, nonatomic) BOOL hardwareEnabled;
@property(assign, nonatomic) BOOL voiceControl;
@property(assign, nonatomic) BOOL alwaysShowMenu;
@property(assign, nonatomic) BOOL openMenuWithSwaggle;
@property(readonly, assign, nonatomic) float touchSpeedMultiplier;
@property(assign, nonatomic) float touchSpeed;
+(id)sharedManager;
+(void)initialize;
-(void)showMenu:(BOOL)menu;
-(CGPoint)rotateEventFromOrientation:(CGPoint)orientation;
-(void)volumeChanged;
-(void)rotateEventToOrientation:(id)orientation;
-(void)thirdButtonPress:(int)press;
-(void)secondButtonPress:(int)press;
-(BOOL)canShowFingers;
-(void)menuExited;
-(void)performTap:(int)tap points:(CGPoint)points;
-(void)notifyUserEventOccurred;
-(void)startPinchModeWithPoint:(CGPoint)point;
-(void)handleMultiTouchStandard:(int)standard withPoint:(CGPoint)point;
-(void)exitedSaveState;
-(void)_updateSavedGestures;
-(void)firstButtonPress:(int)press;
-(void)_startFingerDownTimer;
-(id)_avPlayerForSound:(id)sound;
-(void)_setFingerDownLockEnabled:(BOOL)enabled;
-(BOOL)inCustomGesture;
-(void)hoverMoved:(CGPoint)moved;
-(void)_menuOpenTracker:(CGPoint)tracker;
-(void)setNubbitMoving:(BOOL)moving;
-(void)setCaptureEvents:(BOOL)events;
-(void)_resetMenuOpenTracker;
-(void)prepareCustomGesture:(id)gesture;
-(BOOL)isCapturingRealEvents;
-(void)performCustomGesture:(id)gesture;
-(void)settingsChanged;
-(void)handleAccessibilityFirstResponderChanged;
-(void)handleAccessibilityScreenChange;
-(void)voiceControlWasEnabled:(BOOL)enabled;
-(void)_handlePinchAdjust:(CGPoint)adjust;
-(void)_handleRealPinchAdjust:(CGPoint)adjust startPoint:(CGPoint)point;
-(void)_resetPinchAdjust;
-(void)mediaPlaybackChanged;
-(void)screenshotWillFire;
-(void)mediaControlsChanged:(BOOL)changed;
-(void)orientationChanged;
-(int)deviceOrientation;
-(BOOL)inPinchMode;
-(BOOL)inRockerMode;
-(BOOL)inMultFingerMode;
-(void)performHardwareButton:(int)button state:(int)state;
-(void)systemServerDied;
-(void)substantialTransitonOccurred;
-(void)ringerSwitchChanged;
-(void)handleRealEvent:(GSEventRef)event;
-(BOOL)usingSpecialTool;
-(void)specialToolUsageEnded;
-(BOOL)_shouldHandleRealEventWithMultiTouchTool;
-(void)_handleMultiTouchToolEvent:(GSEventRef)event;
-(void)_handleRealCustomGestureUp:(CGPoint)up;
-(void)_handleRealMultiFingerUp:(CGPoint)up;
-(void)_handleRealCustomGestureMove:(CGPoint)move;
-(void)_handleRealCustomGestureDown:(CGPoint)down;
-(void)_handleRealMultiFingerDown:(CGPoint)down;
-(void)_handleRealMultiFingerMove:(CGPoint)move;
-(void)_handleRealPinchToolMove:(CGPoint)move;
-(void)_handleRealPinchToolUp:(CGPoint)up;
-(void)resetPinch;
-(void)_handleRealPinchToolDown:(CGPoint)down;
-(void)_movePinchToolToPoint:(CGPoint)point;
-(void)moveFingersToPointInFingerCoordinateSpace:(CGPoint)fingerCoordinateSpace allowOutOfBounds:(BOOL)bounds;
-(void)_moveFingersToPoint:(CGPoint)point;
-(void)keyboardVisible:(BOOL)visible withFrame:(CGRect)frame;
-(void)systemServerConnected;
-(void)dealloc;
-(id)init;
@end

