/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "assistivetouchd-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface HNDHoverCursorMark : XXUnknownSuperclass {
	CGAffineTransform _rotationTransform;
	CGRect _originalFrame;
}
@property(assign, nonatomic) CGRect originalFrame;
@property(assign, nonatomic) CGAffineTransform rotationTransform;
-(void)drawRect:(CGRect)rect;
-(void)setFrame:(CGRect)frame;
-(id)initWithFrame:(CGRect)frame;
@end

