/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "assistivetouchd-Structs.h"
#import "HNDWindow.h"


__attribute__((visibility("hidden")))
@interface HNDIgnoredWindow : HNDWindow {
}
-(BOOL)_ignoresHitTest;
@end

