/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "assistivetouchd-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface HNDInnerCircleView : XXUnknownSuperclass {
}
-(void)drawRect:(CGRect)rect;
@end

