/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "assistivetouchd-Structs.h"


__attribute__((visibility("hidden")))
@interface HNDMain {
	CFRunLoopRef _mainRunLoop;
	BOOL _stop;
	BOOL _springboardReady;
	BOOL _keepAlive;
}
@property(assign, nonatomic) BOOL springboardReady;
+(id)commandPath;
+(id)versionString;
+(id)processIdentifier;
-(void)stop;
-(void)_goDogGo:(id)go;
-(void)_initializeSystemSettings;
-(void)_assistiveTouchSettingsChanged;
-(void)_assistiveTouchEnabledChange;
-(int)run;
-(void)setKeepAlive:(BOOL)alive;
-(void)_springBoardDied:(id)died;
-(id)initWithArgc:(int)argc argv:(const char**)argv;
@end

