/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "assistivetouchd-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface HNDMultiFinger : XXUnknownSuperclass {
	BOOL _recorded;
	BOOL _finalized;
	BOOL _imploded;
}
-(void)drawRect:(CGRect)rect;
-(void)_drawCircle:(CGPoint)circle radius:(float)radius color:(id)color;
-(void)setRecorded:(BOOL)recorded;
-(void)explode;
-(void)implode;
-(void)setFinalized:(BOOL)finalized;
-(id)initWithFrame:(CGRect)frame;
@end

