/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "assistivetouchd-Structs.h"
#import "HNDView.h"


__attribute__((visibility("hidden")))
@interface HNDPinchChainView : HNDView {
	CGPoint _startPoint;
	CGPoint _endPoint;
	int pinchChainMode;
}
@property(assign, nonatomic) int pinchChainMode;
@property(assign, nonatomic) CGPoint endPoint;
@property(assign, nonatomic) CGPoint startPoint;
-(void)drawRect:(CGRect)rect;
-(void)drawTails:(CGRect)tails;
-(CGPoint)midPoint;
-(void)_drawTail:(CGPoint)tail rect:(CGRect)rect direction:(BOOL)direction;
-(BOOL)isUserInteractionEnabled;
-(id)initWithFrame:(CGRect)frame;
@end

