/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "assistivetouchd-Structs.h"
#import "HNDView.h"
#import "HNDRockerButtonDataSource.h"

@class HNDRockerButton, UIImageView, NSMutableArray, HNDFingerView, HNDVolumeBar, AXTimer, CADisplayLink;

__attribute__((visibility("hidden")))
@interface HNDRocker : HNDView <HNDRockerButtonDataSource> {
	int _state;
	NSMutableArray* _rockerItems;
	HNDRockerButton* _selectedButton;
	HNDRockerButton* _backButton;
	int _selectedButtonIndex;
	int _backgroundType;
	HNDFingerView* _middleCircle;
	CGPoint _initialPoint;
	BOOL _isFullMenuVisible;
	BOOL _isNubbitVisible;
	BOOL _useCircle;
	float _progress;
	BOOL _sentRockers;
	BOOL _linkRunning;
	CADisplayLink* _rockerLink;
	double _startInterval;
	AXTimer* _homeButtonDismissTimer;
	UIImageView* _background;
	int _style;
	BOOL _nubbitDimmed;
	AXTimer* _nubbitFadeTimer;
	UIImageView* _nubbitForeground;
	BOOL _animatingNubbit;
	AXTimer* _volumeHideTimer;
	AXTimer* _volumeUpdateTimer;
	HNDVolumeBar* _volumeBar;
	CGPoint _nubbitPosition;
}
@property(assign, nonatomic) CGPoint nubbitPosition;
@property(assign, nonatomic) int style;
+(CGSize)nubbitSize;
+(CGSize)initialRockerSize;
-(XXStruct_n9corA)rockerButtonGuttersForRockerButton:(id)rockerButton;
-(id)accessibilityHint;
-(id)accessibilityLabel;
-(BOOL)isAccessibilityElement;
-(BOOL)accessibilityPerformEscape;
-(void)setNubbitVisible:(BOOL)visible;
-(void)transitionNubbitToMenu:(CGPoint)menu animationCompleted:(id)completed;
-(void)transitionMenuToNubbit:(CGPoint)nubbit changeAlpha:(BOOL)alpha animate:(BOOL)animate;
-(void)highlightNubbit;
-(void)fadeNubbit;
-(void)_resetVisibility:(BOOL)visibility;
-(void)_initializeNubbit;
-(void)setFullMenuVisible:(BOOL)visible atPoint:(CGPoint)point;
-(BOOL)isFullMenuVisible;
-(CGPoint)onScreenLocation;
-(void)_homeButton:(BOOL)button;
-(void)_handleRotate:(int)rotate;
-(void)_orientationPressed;
-(void)_shakePressed;
-(void)_ringerPressed;
-(void)_volumeDown:(BOOL)down;
-(void)_volumeUp:(BOOL)up;
-(void)_updateVolumeDisplay;
-(void)_lockButton:(BOOL)button;
-(void)_morePressed;
-(void)_hardwareButtonPressed;
-(void)_handleTouch:(int)touch;
-(void)_multiTasking;
-(void)_screenshotPressed;
-(void)_tripleClickHomePressed;
-(void)_siriButtonPressed;
-(void)_voiceControlPressed;
-(void)_pinchPressed;
-(void)_gesturesPressed;
-(void)_favoritesPressed;
-(void)_loadMenuItems:(BOOL)items;
-(void)_resetHoverCircleLocation;
-(void)setUseCircleMode:(BOOL)mode;
-(void)_layoutMenuItems:(BOOL)items;
-(void)_setBackgroundWithType:(int)type;
-(void)_layoutFourRockers;
-(void)_layoutRotationRockers;
-(void)_layoutArbitraryRockers;
-(void)_layoutFiveOrSixRockers;
-(void)_layoutEightRockers;
-(void)_layoutBackButton;
-(CGPathRef)_pieSlice:(int)slice withSlices:(int)slices;
-(void)_resetRockerButtons;
-(void)_layoutButton:(id)button withPoint:(CGPoint)point;
-(void)_loadFavoritesMenuItems;
-(void)_swipePressed;
-(void)_addFavoriteBoxPressed;
-(void)_customGesturePressed:(id)pressed;
-(void)_loadHardwareMenuItems;
-(void)updateRingerSwitch;
-(void)_loadRotateMenuItems;
-(void)_loadGesturesMenuItems;
-(void)_loadMoreMenuItems;
-(void)_loadInitialMenuItems;
-(void)cleanup;
-(void)handleRealUpEvent:(CGPoint)event;
-(BOOL)isAnimatingNubbit;
-(void)handleRealDownEvent:(CGPoint)event;
-(void)performPress:(int)press type:(int)type;
-(void)_goBackInMenuState:(int)menuState;
-(void)showVolumeBar:(BOOL)bar withProgress:(float)progress;
-(void)volumeChanged;
-(void)modalizeMenu:(BOOL)menu modalButton:(id)button;
-(void)implodeDisplayLinkFired:(id)fired;
-(BOOL)hoveredTo:(CGPoint)to;
-(void)_updateSelectedButton;
-(id)_rockerHitTest:(CGPoint)test;
-(BOOL)_angleIndicatesReturnToCenter:(float)center;
-(void)_highlightRockerButtonAtAngle:(float)angle;
-(int)_indexForAngle:(float)angle;
-(void)dealloc;
-(void)_updateProgress:(id)progress;
-(id)rockerButtons;
-(void)showMiddleCircle:(BOOL)circle;
-(id)initWithFrame:(CGRect)frame;
@end

