/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "assistivetouchd-Structs.h"

@protocol HNDRockerButtonDataSource <NSObject>
-(XXStruct_n9corA)rockerButtonGuttersForRockerButton:(id)rockerButton;
@end

