/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "assistivetouchd-Structs.h"
#import "HNDView.h"

@class NSString, UILabel, UIImageView;
@protocol HNDRockerButtonDataSource;

__attribute__((visibility("hidden")))
@interface HNDRockerButton : HNDView {
	id _downBlock;
	id _upBlock;
	NSString* _title;
	BOOL _selected;
	BOOL _highlighted;
	UILabel* _label;
	NSString* _imageName;
	UIImageView* _imageView;
	BOOL _isEmptyFavorite;
	BOOL _customTitle;
	BOOL _isBackButton;
	float _spacingBetweenText;
	CGPathRef hitPath;
	BOOL isEmptyFavorite;
	BOOL customTitle;
	BOOL isModalDown;
	CGPoint _textOffset;
	BOOL _maxNumberOfLines;
	id<HNDRockerButtonDataSource> _dataSource;
}
@property(assign, nonatomic) id<HNDRockerButtonDataSource> dataSource;
@property(assign, nonatomic) CGPoint textOffset;
@property(assign, nonatomic) float spacingBetweenText;
@property(assign, nonatomic) BOOL isBackButton;
@property(assign, nonatomic) BOOL maxNumberOfLines;
@property(assign, nonatomic) BOOL customTitle;
@property(assign, nonatomic) BOOL isEmptyFavorite;
@property(retain, nonatomic) CGPathRef hitPath;
@property(assign, nonatomic) BOOL highlighted;
@property(assign, nonatomic) BOOL selected;
@property(assign, nonatomic) BOOL isModalDown;
@property(copy, nonatomic) id downBlock;
@property(copy, nonatomic) id upBlock;
@property(retain, nonatomic) NSString* title;
+(id)buttonWithTitle:(id)title imageName:(id)name downBlock:(id)block upBlock:(id)block4 dataSource:(id)source;
-(id)accessibilityLabel;
-(BOOL)isAccessibilityElement;
-(void)dealloc;
-(void)layoutSubviews;
-(void)_drawPixels;
-(CGRect)adjustTextForActualFrame:(CGRect)actualFrame withSuggestedFrame:(CGRect)suggestedFrame;
-(void)updateTextColor;
-(id)currentImage;
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
-(void)performPress:(BOOL)press;
-(void)handleRealUpEvent:(CGPoint)event;
-(void)handleRealCancelEvent:(CGPoint)event;
-(void)handleFingerDriftedAway;
-(void)handleRealDownEvent:(CGPoint)event;
-(void)setImageName:(id)name;
-(void)_updateImage;
-(id)initWithImageName:(id)imageName;
@end

