/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "assistivetouchd-Structs.h"

@protocol HNDViewDelegateControl;

__attribute__((visibility("hidden")))
@interface HNDView : UIView {
	BOOL _active;
	id<HNDViewDelegateControl> _controlDelegate;
}
@property(assign, nonatomic) BOOL isActive;
@property(assign) id<HNDViewDelegateControl> controlDelegate;
-(id)description;
-(void)handleRealDownEvent:(CGPoint)event;
-(void)handleRealMoveEvent:(CGPoint)event;
-(void)handleRealUpEvent:(CGPoint)event;
-(void)handleRealCancelEvent:(CGPoint)event;
-(void)handleFingerDriftedAway;
@end

