/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "assistivetouchd-Structs.h"
#import "HNDView.h"


__attribute__((visibility("hidden")))
@interface HNDVolumeBar : HNDView {
	float _progress;
}
@property(assign, nonatomic) float progress;
-(void)drawRect:(CGRect)rect;
-(id)initWithFrame:(CGRect)frame;
@end

