/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import "assistivetouchd-Structs.h"

@protocol HNDWindowDelegateProtocol <NSObject>
-(BOOL)acceptsHitTest:(CGPoint)test;
@end

