/**
 * This header is generated by class-dump-z 0.2b.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface XXUnknownSuperclass (HNDView)
-(id)_axSubviews;
-(void)_axPrintSubviews:(int)subviews string:(id)string;
@end

